on:
  workflow_dispatch:
  
jobs:
  get-structure:
    runs-on: ubuntu-latest
    steps:

      - name: 初始化源码仓库
        run: |
          rm -rf kernel_workspace && mkdir kernel_workspace && cd kernel_workspace
          mkdir common
          cd kernel_workspace/common
          pwd
          ls

      
